server:
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp
  redis:
    port: 56379
    host: localhost

spring:
  data:
    jpa:
      repositories:
        enabled: true
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
       ddl-auto: create-drop

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true